# Generated by Django 5.0.1 on 2025-12-13 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('daily_active_users', models.IntegerField(default=0)),
                ('new_signups', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('new_listings', models.IntegerField(default=0)),
                ('total_active_listings', models.IntegerField(default=0)),
                ('listings_sold', models.IntegerField(default=0)),
                ('average_listings_per_user', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('messages_sent', models.IntegerField(default=0)),
                ('new_conversations', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('average_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Metric',
                'verbose_name_plural': 'Platform Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('actions_performed', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-session_start'],
            },
        ),
    ]
