# Generated by Django 5.0.1 on 2025-12-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific attributes as key-value pairs'),
        ),
    ]
