# Generated by Django 5.0.1 on 2025-12-14 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category_image_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or Misleading'), ('inappropriate', 'Inappropriate Content'), ('fraud', 'Suspected Fraud'), ('duplicate', 'Duplicate Listing'), ('sold', 'Already Sold (Not Removed)'), ('wrong_category', 'Wrong Category'), ('fake_price', 'Fake or Misleading Price'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Please provide details about this report')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('action_taken', models.CharField(blank=True, help_text='Action taken by admin (e.g., Listing deactivated, Warning sent, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_li_status_79c206_idx'), models.Index(fields=['listing', '-created_at'], name='listings_li_listing_82012d_idx')],
                'unique_together': {('listing', 'reporter')},
            },
        ),
    ]
