# Generated by Django 5.0.1 on 2025-12-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_area_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Anonymous username for listings', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='show_real_name',
            field=models.BooleanField(default=True, help_text='Show real name in listings'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(help_text='City name', max_length=100),
        ),
    ]
