# Generated by Django 5.0.1 on 2025-12-13 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_new_company_listings',
            field=models.BooleanField(default=True, help_text='Email me when new items are listed in my company'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_unread_messages',
            field=models.BooleanField(default=True, help_text='Email me about unread messages after 15 minutes'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, default='abcd@hello.com', help_text='Personal email for notifications', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
