# Generated by Django 5.0.1 on 2025-12-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_reminder_sent',
            field=models.BooleanField(default=False, help_text='Email sent after 15 min if unread'),
        ),
    ]
